FROM python:3.11

# Adding trusting keys to apt for repositories
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -

# Adding Google Chrome to the repositories
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'

# Updating apt to see and install Google Chrome
RUN apt-get -y update

# Install necessary packages
RUN apt-get install -y unzip google-chrome-stable python3 wget python3-venv xvfb

# Debug step: Print the installed Chrome version
RUN google-chrome --version

# Clean up any existing Chromedriver installations
RUN rm -f /usr/local/bin/chromedriver

# Download and install the matching ChromeDriver
RUN LATEST_CHROMEDRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE") && \
    echo "Detected latest Chromedriver version: $LATEST_CHROMEDRIVER_VERSION" && \
    wget -q -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver_linux64.zip" && \
    unzip /tmp/chromedriver.zip -d /usr/local/bin/ && \
    rm /tmp/chromedriver.zip && \
    ln -fs /usr/local/bin/chromedriver /usr/bin/chromedriver

# Set display port as an environment variable
ENV DISPLAY=:99

# Set the working directory
WORKDIR /app

# Set up a virtual environment
RUN python3 -m venv venv

# Activate the virtual environment and install pip and selenium
RUN /app/venv/bin/pip install --upgrade pip
RUN /app/venv/bin/pip install selenium

# Copy the requirements.txt and install dependencies in the virtual environment
COPY requirements.txt .
RUN /app/venv/bin/pip install -r requirements.txt

# Copy the rest of the application code
COPY . .

# Print working directory and list files for debugging
RUN echo "Current working directory:" && pwd
RUN echo "Listing files in /app:" && ls -la /app

# Start Xvfb and specify the entry point for the application using the virtual environment's Python
CMD ["/bin/bash", "-c", "rm -rf /tmp/.X99-lock && Xvfb :99 -ac & /app/venv/bin/python main.py"]